### ISSUE TITLE
Relative import paths in test files

### ISSUE THREAD

**Issue by PeetV** [akeanewow/DataWhistle#13]

**Comment by mwood2** [comment]
Hey Jin,

Came across a similar issue to this when trying to run the tests in markdown. Here was the fix if it helps (DataWhistle setup is a bit different though):

import sys
import os
PACKAGE_PARENT = '..'
SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__))))
sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))

**Comment by PeetV** [comment]
Implemented
