### ISSUE TITLE
Add a datetime column type specified with a format string

### ISSUE THREAD

**Issue by PeetV** [akeanewow/DataWhistle#6]
Use Pandas to_datetime function to covert a column before applying checks:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html

**Comment by mwood2** [comment]
Adding to the below options to a column. Missing format will auto interpret the format.

type: datetime
format: %Y%m%d

**Comment by PeetV** [comment]
Awesome work Morgan!
